permissions:
  packages: write

name: Release
on:
  push:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Pack CLI
        run: |
          sudo add-apt-repository ppa:cncf-buildpacks/pack-cli
          sudo apt-get update
          sudo apt-get install pack-cli

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image using Buildpacks
        run: |
          pack build ghcr.io/octopussolutionsengineering/ghu2024sampleapp --builder gcr.io/buildpacks/builder:v1 --path .
          docker push ghcr.io/octopussolutionsengineering/ghu2024sampleapp:latest